services:

  api:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./app:/code/app
    env_file:
      - ./.env

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - app-db-data:/var/lib/postgresql/pgdata

volumes:
  app-db-data:
