services:

  api:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./app:/code/app
    env_file:
      - ./.env
    command: fastapi dev app/main.py --host 0.0.0.0 --port 80

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - app-db-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    
volumes:
  app-db-data:
